#include "Controllino.h"

#define LIGHT_ANALOG_OUT_0 CONTROLLINO_AO0
#define LIGHT_ANALOG_OUT_1 CONTROLLINO_AO1
#define LIGHT_ANALOG_OUT_2 CONTROLLINO_R9
#define LIGHT_DIGITAL_OUT_0 CONTROLLINO_R9
#define LIGHT_DIGITAL_OUT_1 CONTROLLINO_R8
#define LIGHT_DIGITAL_OUT_2 CONTROLLINO_R7

#define NEST_DIGITAL_OUT CONTROLLINO_DO0
#define CHICKEN_GATE_DIGITAL_OUT CONTROLLINO_DO2
#define WATER_BTN CONTROLLINO_DI0
#define WATER_VALVE_DO CONTROLLINO_DO1
#define FEED_SENSOR_DI CONTROLLINO_DI1
#define FEED_TRANSPORT_MOTOR_DO CONTROLLINO_DO3
#define ALARM_OUT CONTROLLINO_DO4
#define ALARM_SIRENE CONTROLLINO_R8