#include "Controllino.h"

#define LIGHT_ANALOG_OUT_0 CONTROLLINO_D9
#define LIGHT_ANALOG_OUT_1 CONTROLLINO_D10
#define LIGHT_ANALOG_OUT_2 CONTROLLINO_D11
#define LIGHT_DIGITAL_OUT_0 CONTROLLINO_R9
#define NEST_DIGITAL_OUT CONTROLLINO_D0
#define CHICKEN_GATE_DIGITAL_OUT CONTROLLINO_D2
#define WATER_BTN CONTROLLINO_A1
#define WATER_VALVE_DO CONTROLLINO_D1
#define FEED_SENSOR_DI CONTROLLINO_IN0
#define FEED_TRANSPORT_MOTOR_DO CONTROLLINO_D3
#define ALARM_OUT CONTROLLINO_D0
#define ALARM_SIRENE CONTROLLINO_R5
