#include "Controllino.h"

#define LIGHT_ANALOG_OUT_0 CONTROLLINO_D0
#define LIGHT_ANALOG_OUT_1 CONTROLLINO_D1
#define LIGHT_ANALOG_OUT_2 CONTROLLINO_D2
#define LIGHT_DIGITAL_OUT_0 CONTROLLINO_D2
#define NEST_DIGITAL_OUT CONTROLLINO_D3
#define WATER_BTN CONTROLLINO_A0
#define WATER_VALVE CONTROLLINO_D4