#include "Controllino.h"

#define LIGHT_ANALOG_OUT_0 CONTROLLINO_AO0
#define LIGHT_ANALOG_OUT_1 CONTROLLINO_AO1
#define LIGHT_ANALOG_OUT_2 CONTROLLINO_R9
#define LIGHT_DIGITAL_OUT_0 CONTROLLINO_R9
#define NEST_DIGITAL_OUT CONTROLLINO_DO0
#define WATER_BTN CONTROLLINO_DI0
#define WATER_VALVE CONTROLLINO_DO1